GET http://localhost:3000

### SignUp
###Login Route
POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
  "email": "jacnd1gmail.",
  "password": "123",
  "name": "pawan"
}
### signIn 
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "jacnd1@gmail.com",
  "password": "1234",
   
  
}
###

POST http://localhost:3000/api/google-signin
Content-Type: application/json

{
  "email": "jack@gmail.com",
  "password": "123"
}